"""Deterministic Lua bundler. Deployment is explicit and backs up both controllers."""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
from datetime import datetime

ROOT = Path(__file__).resolve().parent
MODULES = ('core', 'adapter', 'map', 'threat', 'navigation', 'hero', 'items',
           'support', 'modes', 'executor', 'arbiter', 'api', 'json', 'bridge', 'chat', 'ui', 'main')

def bundle() -> Path:
    license_text = (ROOT / 'OPENHYPERAI_LICENSE').read_text(encoding='utf-8')
    chunks = ['-- GENERATED by build_bot.py. Edit src/*.lua, not this file.\n',
              '-- OpenHyperAI reference commit: cb814c6c8dc51ed08045d6efd9f4a48147992711\n',
              '--[[\n' + license_text + '\n]]\nlocal B = {}\n']
    manifest = {}
    for name in MODULES:
        code = (ROOT / 'src' / f'{name}.lua').read_text(encoding='utf-8-sig')
        line = ''.join(chunks).count('\n') + 1
        manifest[name] = {'line': line + 3, 'sha256': hashlib.sha256(code.encode()).hexdigest()}
        chunks.append(f'\n-- MODULE: src/{name}.lua\ndo\nlocal initialize = (function()\n{code}\nend)()\ninitialize(B)\nend\n')
    chunks.append('\nreturn B.script\n')
    dest = ROOT / 'dist/spirit_breaker_bot.lua'
    dest.parent.mkdir(exist_ok=True)
    dest.write_text(''.join(chunks), encoding='utf-8', newline='\n')
    (dest.parent / 'manifest.json').write_text(json.dumps(manifest, indent=2), encoding='utf-8')
    subprocess.run(['node', str(ROOT / 'tools/check_lua.cjs'), str(dest)], cwd=ROOT, check=True)
    print(f'Built {dest} ({dest.stat().st_size} bytes)')
    return dest

def deploy(source: Path, scripts: Path) -> None:
    scripts = scripts.resolve(strict=True)
    if not scripts.is_dir() or scripts != Path('C:/Umbrella/scripts').resolve():
        raise ValueError('Deployment target must be the explicitly requested C:/Umbrella/scripts')
    backup = ROOT / 'archive' / ('pre-rulebased-' + datetime.now().strftime('%Y%m%d-%H%M%S-%f'))
    backup.mkdir(parents=True)
    target = scripts / source.name
    for old in (scripts / 'mid_t1_start.lua', target):
        if old.is_file():
            shutil.copy2(old, backup / old.name)
    # Keep old controller entirely outside scripts so two active Lua files cannot fight.
    old = scripts / 'mid_t1_start.lua'
    if old.exists():
        old.unlink()  # Already copied into the unique, verified backup above.
    temp = scripts / (source.name + '.pending')
    try:
        shutil.copy2(source, temp)
        temp.replace(target)
    except Exception:
        if (backup / 'mid_t1_start.lua').exists():
            shutil.copy2(backup / 'mid_t1_start.lua', old)
        raise
    if hashlib.sha256(target.read_bytes()).digest() != hashlib.sha256(source.read_bytes()).digest():
        raise RuntimeError('Deployment hash mismatch')
    print(f'Deployed: {target}\nPrevious controllers backed up: {backup}')

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--deploy', action='store_true')
    args = parser.parse_args()
    artifact = bundle()
    if args.deploy:
        deploy(artifact, Path('C:/Umbrella/scripts'))
